const mongoose = require('mongoose');
const Schema = mongoose.Schema;

/**
 * Task 1: Question Model
 * Represents a single question in the quiz
 * - Object_id: Unique identifier for the question (auto-generated by MongoDB)
 * - text: The text of the question
 * - Author: ObjectId referenced from User (identifies who created the question)
 * - options: An array of answer options for the question
 * - keywords: An array of keywords for the question
 * - correctAnswerIndex: Index of the correct answer within the options array
 */
const questionSchema = new Schema({
  text: {
    type: String,
    required: true
  },

  options: [{
    type: String,
    required: true
  }],

  keywords: [{
    type: String
  }],

  correctAnswerIndex: {
    type: Number,
    required: true
  },

  // Task 1: Author field references User ObjectId
  author: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'User'
  }
});

module.exports = mongoose.model('Question', questionSchema);